apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc
  namespace: lab3
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
