apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-local
  namespace: lab3
  annotations:
    volume.beta.kubernetes.io/storage-class: localstorage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi